name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Check out repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify your required Python version

    # Step 3: Install the package from the repository
    - name: Install your package
      run: |
        python -m pip install --upgrade pip
        pip install .  # Installs the package in the current repository

    # Step 4: Install Sphinx and dependencies
    - name: Install Sphinx
      run: |
        pip install -r docs/requirements.txt

    # Step 5: Build the Sphinx documentation
    - name: Build Sphinx documentation
      run: sphinx-build -b html docs/ docs/_build/html

    # Step 6: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
